// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1a32mr5sxtSiWCFLMq1a9K3oB0zSO6nI',
    appId: '1:1008102589541:web:0c0674aac6120780a9f28c',
    messagingSenderId: '1008102589541',
    projectId: 'halal-nikah-2022',
    authDomain: 'halal-nikah-2022.firebaseapp.com',
    storageBucket: 'halal-nikah-2022.appspot.com',
    measurementId: 'G-DG523PGZL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_8EUTCTUYWMlRbZKbOh0FU-xAFBLgm1c',
    appId: '1:1008102589541:android:22cdc616717669c2a9f28c',
    messagingSenderId: '1008102589541',
    projectId: 'halal-nikah-2022',
    storageBucket: 'halal-nikah-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgK7NrlCiYz8JrhnswtoX3tGQ5EbxoBfk',
    appId: '1:1008102589541:ios:e069aec45adf27cba9f28c',
    messagingSenderId: '1008102589541',
    projectId: 'halal-nikah-2022',
    storageBucket: 'halal-nikah-2022.appspot.com',
    androidClientId: '1008102589541-g2vle5ii6fskc63hr4bb0b1gsf775hul.apps.googleusercontent.com',
    iosBundleId: 'com.example.nybal',
  );
}
